# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build-python36:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: set venv and deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -r "docs/src/requirements.txt"
            pip install wheel
            pip install pytest
            pip install flake8

      - run:
          name: install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest .

      - run:
          name: run docs tests
          command: |
            . venv/bin/activate
            cd docs/src
            sphinx-build -b doctest . "../build"

      - run:
          name: build docs
          command: |
            . venv/bin/activate
            cd docs/src
            sphinx-build -b html . "../buildhtml"

      - run:
          name: run sdist bdist
          command: |
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel

      - run:
          name: run flake
          command: |
            . venv/bin/activate
            flake8 compimg

  build-python37:
    docker:
      - image: circleci/python:3.7

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: set venv and deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -r "docs/src/requirements.txt"
            pip install wheel
            pip install pytest
            pip install flake8

      - run:
          name: install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest .

      - run:
          name: run docs tests
          command: |
            . venv/bin/activate
            cd docs/src
            sphinx-build -b doctest . "../build"

      - run:
          name: build docs
          command: |
            . venv/bin/activate
            cd docs/src
            sphinx-build -b html . "../buildhtml"

      - run:
          name: run sdist bdist
          command: |
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel

      - run:
          name: run flake
          command: |
            . venv/bin/activate
            flake8 compimg

  build-python38:
    docker:
      - image: circleci/python:3.8

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: set venv and deps
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install --upgrade setuptools
            pip install -r "docs/src/requirements.txt"
            pip install wheel
            pip install pytest
            pip install flake8

      - run:
          name: install
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -e .

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest .

      - run:
          name: run docs tests
          command: |
            . venv/bin/activate
            cd docs/src
            sphinx-build -b doctest . "../build"

      - run:
          name: build docs
          command: |
            . venv/bin/activate
            cd docs/src
            sphinx-build -b html . "../buildhtml"

      - run:
          name: run sdist bdist
          command: |
            . venv/bin/activate
            python3 setup.py sdist bdist_wheel

      - run:
          name: run flake
          command: |
            . venv/bin/activate
            flake8 compimg

workflows:
  version: 2
  build:
    jobs:
      - build-python36
      - build-python37
      - build-python38
